;;; $DOOMDIR/modules/org.el -*- lexical-binding: t; -*-

(setq org-directory "~/org/")
(after! org
  (setq org-startup-with-inline-images t)
  (setq +org-startup-with-animated-gifs t)
  (setq org-startup-with-latex-preview t)
  (setq org-hide-emphasis-markers t)
  (setq org-link-descriptive t)
  (setq org-pretty-entities t)
  (setq org-hidden-keywords t)
  (setq org-appear-autoemphasis t)
  (setq org-appear-autolinks t)
  (setq org-appear-autosubmarkers t)
  (setq org-appear-autoentities t)
  (setq org-appear-autokeywords t)
  (setq org-appear-inside-latex t)
  (setq org-modern-star nil))
(add-hook 'org-mode-hook
          (lambda ()
            (solaire-mode -1)
            (display-line-numbers-mode -1)
            (mixed-pitch-mode 1)
            (org-fragtog-mode 1)
            (org-appear-mode 1)
            (org-indent-mode -1)
            (org-modern-mode 1)))
(add-hook 'doom-docs-mode-hook
          (lambda ()
            (mixed-pitch-mode 1)))
;; (evil-set-initial-state 'org-mode 'insert)
