# --- syntax colours ---------------------------------------------------------
"comment"            = { fg = "grey",    modifiers = ["italic"] }
"string"             = { fg = "green" }
"constant"           = { fg = "orange" }      # numbers, enums, etc.
"keyword"            = { fg = "purple",  modifiers = ["bold"] }
"type"               = { fg = "light_blue" }
"function"           = { fg = "blue"  }
"variable"           = { fg = "fg" }
"punctuation"        = { fg = "fg" }
# Diff scopes
"diff.plus"          = { fg = "diff_add"    }
"diff.minus"         = { fg = "diff_delete" }
"diff.delta"         = { fg = "diff_change" }

# --- interface colours ------------------------------------------------------
"ui.background"          = { fg = "fg",      bg = "bg0" }
"ui.cursor"              = { fg = "bg0", bg = "fg" }
"ui.cursor.match"        = { fg = "bg0", bg = "fg" }
"ui.selection"           = { fg = "red",     bg = "red" }
"ui.selection.primary"   = { bg = "red" }
"ui.linenr"              = { fg = "grey" }
"ui.linenr.selected"     = { fg = "yellow" }
"ui.statusline"          = { fg = "fg",      bg = "bg1" }
"ui.statusline.inactive" = { fg = "grey",    bg = "bg_d" }
"diagnostic.error"       = { fg = "red" }
"diagnostic.warning"     = { fg = "yellow" }
"diagnostic.info"        = { fg = "cyan" }
"diagnostic.hint"        = { fg = "light_grey" }

[palette]
contrast = '#111210'
inverse = '#ffffff'
bg0 = '#252623'
bg1 = '#2f312c'
bg2 = '#383b35'
bg3 = '#3a3d37'
bg_d = '#1c1e1b'
bg_blue = '#68aee8'
bg_yellow = '#e2c792'
fg = '#f1e9d2'
purple = '#aaaaff'
bright_purple = '#df73ff'
green = '#8fb573'
orange = '#ff9966'
blue = '#57a5e5'
light_blue = '#96c7ef'
yellow = '#dbb651'
cyan = '#70c2be'
red = '#e75a7c'
coral = '#f08080'
grey = '#5b5e5a'
light_grey = '#838781'
diff_add = '#40531b'
diff_delete = '#893f45'
diff_change = '#2a3a57'
diff_text = '#3a4a67'
