theme = "onedarker"

[editor]
idle-timeout = 10
cursorline = true
color-modes = true
text-width = 100

[editor.statusline]
left = ["mode", "spinner", "file-type", "file-name", "read-only-indicator", "file-modification-indicator"]
right = ["diagnostics", "selections", "register", "version-control", "spacer", "position-percentage", "position", "file-encoding"]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "hint"
